# Generated by Django 3.0 on 2021-09-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_questions_ans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('clg', models.CharField(max_length=200)),
                ('regdno', models.CharField(max_length=100)),
                ('rollno', models.IntegerField()),
                ('email', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('branch', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('EEE', 'EEE'), ('E&I', 'E&I')], max_length=50)),
                ('psw', models.CharField(max_length=25)),
                ('repsw', models.CharField(max_length=25)),
            ],
        ),
    ]
