# Generated by Django 3.0 on 2021-09-21 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_auto_20210921_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
