# Generated by Django 3.0 on 2021-09-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0007_auto_20210921_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marksheet',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='regdno',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Guest'), (2, 'Professor'), (3, 'Student')], default=1),
        ),
    ]
